using System.Text.Json.Serialization;

namespace DataBase.Dtos
{
    public class TaskDto
    {
        [JsonIgnore] // we're ignoring id, so it doesn't show in Swagger. Id is automatically generated by the database
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [JsonIgnore]
        public bool Finished { get; set; } = false;
        public DateTime DueDate { get; set; }
        public int ProjectId { get; set; }
        public int? AsigneeID { get; set; } // ID of the user responsible for the task. Can be null at initialization
    }
}
