using Utils.Enums;
using System.Text.Json.Serialization;

namespace DataBase.Dtos
{
    public class UserDto
    {
        [JsonIgnore] // we're ignoring id, so it doesn't show in Swagger. Id is automatically generated by the database
        public int? Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
    }
}
